# Generated by Django 4.2 on 2025-06-09 05:48

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_slug_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to=main.models.project_gallery_upload_to)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.project')),
            ],
            options={
                'verbose_name_plural': 'Project Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
