# Generated by Django 4.2 on 2025-06-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projectgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', 'Lập Kế Hoạch'), ('design', 'Thiết Kế'), ('production', 'Sản Xuất'), ('installation', 'Lắp Đặt'), ('completed', 'Hoàn Thành')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Tiến độ phần trăm (0-100)')),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='main.project')),
            ],
            options={
                'ordering': ['project', 'order', 'created_at'],
            },
        ),
    ]
