# Generated by Django 5.2.3 on 2025-06-15 09:03

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_simplify_projecttimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục tin tức',
                'verbose_name_plural': 'Danh mục tin tức',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(help_text='Mô tả ngắn về bài viết (tối đa 500 ký tự)', max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(upload_to=main.models.news_image_upload_to, verbose_name='Hình ảnh chính')),
                ('image_position', models.CharField(choices=[('left', 'Bên trái'), ('right', 'Bên phải'), ('top', 'Phía trên'), ('full', 'Toàn màn hình'), ('center', 'Giữa bài viết')], default='top', max_length=10, verbose_name='Vị trí hình ảnh')),
                ('image_caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích hình ảnh')),
                ('external_link', models.URLField(blank=True, help_text='Link tham khảo hoặc nguồn tin', verbose_name='Liên kết ngoài')),
                ('external_link_text', models.CharField(blank=True, help_text='Văn bản hiển thị cho liên kết ngoài', max_length=100, verbose_name='Văn bản liên kết')),
                ('tags', models.CharField(blank=True, help_text='Các thẻ phân cách bằng dấu phẩy', max_length=255, verbose_name='Thẻ')),
                ('featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='published', max_length=10, verbose_name='Trạng thái')),
                ('author', models.CharField(default='VAV Furniture', max_length=100, verbose_name='Tác giả')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.newscategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
