# Generated by Django 5.2.3 on 2025-07-09 08:54

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newscategory_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Văn Bản'), ('image', 'Hình Ảnh'), ('text_image', 'Văn Bản & Hình Ảnh')], default='text', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.product_detail_image_upload_to)),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_contents', to='main.product')),
            ],
            options={
                'verbose_name': 'Product Detail Content',
                'verbose_name_plural': 'Product Detail Contents',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
